"""Planner Agent decomposing ResearchGoal into a validated ResearchPlan DAG."""

import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.common.enums import AgentRole, EdgeType, TaskType
from app.common.errors import DAGValidationError, ResearchMindError
from app.intelligence.protocols import LLMClientProtocol
from app.state.models import (
    DependencyEdge,
    PlanMetadata,
    ResearchGoal,
    ResearchPlan,
    SubtaskNode,
)
from app.tasks.dag import DAGValidator, ValidatedDAG


class PlannerError(ResearchMindError):
    """Raised when research goal decomposition or plan formulation fails."""

    def __init__(self, message: str, details: dict[str, Any] | None = None) -> None:
        super().__init__(message, details)


class PlannedSubtask(BaseModel):
    """Atomic task specification generated by LLM decomposition."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    subtask_id: str = Field(
        ..., min_length=1, description="Unique identifier for the subtask"
    )
    task_type: TaskType = Field(
        default=TaskType.WEB_SEARCH, description="Classification of the subtask"
    )
    objective: str = Field(
        ..., min_length=1, description="Concrete goal of this subtask"
    )
    search_queries: tuple[str, ...] = Field(
        default_factory=tuple, description="Initial search keywords or queries"
    )
    assigned_role: AgentRole = Field(
        default=AgentRole.RESEARCHER, description="Assigned agent specialist role"
    )
    prerequisite_ids: tuple[str, ...] = Field(
        default_factory=tuple,
        description="IDs of prerequisite subtasks that must complete before this subtask",
    )
    timeout_seconds: int = Field(
        default=120, ge=5, le=3600, description="Task execution timeout in seconds"
    )
    max_retries: int = Field(
        default=3, ge=0, le=10, description="Maximum retry attempts on task failure"
    )
    input_context: dict[str, Any] = Field(
        default_factory=dict, description="Contextual parameters or dependencies"
    )


class PlannedDecomposition(BaseModel):
    """Structured LLM output schema containing the full task graph decomposition."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    rationale: str = Field(
        default="", description="Strategic reasoning for the subtask graph topology"
    )
    subtasks: tuple[PlannedSubtask, ...] = Field(
        ..., min_length=1, description="List of decomposed subtask nodes"
    )


PLANNER_SYSTEM_PROMPT = """You are an expert autonomous research planner and task architect.
Your objective is to decompose a high-level research goal into a structured, dependency-aware execution Directed Acyclic Graph (DAG).

Guidelines:
1. Decompose the research inquiry into discrete, atomic, and falsifiable subtasks.
2. Assign each subtask to the most appropriate agent role (e.g. researcher, analyst, verifier, evaluator, reporter).
3. Specify exact dependency prerequisites (prerequisite_ids) so prerequisite tasks complete before dependent analysis or verification tasks.
4. Ensure the dependency graph is strictly acyclic with no self-dependencies or dangling references.
5. Limit the total number of subtasks to the requested max_subtasks bound.
"""


class PlannerAgent:
    """Framework-agnostic planning agent responsible for research goal DAG formulation."""

    def __init__(
        self,
        llm_client: LLMClientProtocol,
        validator: DAGValidator | None = None,
    ) -> None:
        self.llm_client = llm_client
        self.validator = validator or DAGValidator()

    def _build_user_prompt(self, goal: ResearchGoal) -> str:
        domain_str = ", ".join(goal.domain_tags) if goal.domain_tags else "general"
        constraints_str = (
            ", ".join(f"{k}={v}" for k, v in goal.constraints.items())
            if goal.constraints
            else "none"
        )
        return (
            f"Research Goal: {goal.query}\n"
            f"Target Domains: {domain_str}\n"
            f"Constraints: {constraints_str}\n"
            f"Max Subtasks Allowed: {goal.max_subtasks}\n\n"
            f"Please produce a fully structured task decomposition DAG."
        )

    async def plan(
        self,
        goal: ResearchGoal,
        run_id: str | None = None,
        plan_id: str | None = None,
    ) -> ResearchPlan:
        """Decompose a ResearchGoal into a validated ResearchPlan."""
        plan, _ = await self.plan_and_validate(goal, run_id=run_id, plan_id=plan_id)
        return plan

    async def plan_and_validate(
        self,
        goal: ResearchGoal,
        run_id: str | None = None,
        plan_id: str | None = None,
    ) -> tuple[ResearchPlan, ValidatedDAG]:
        """Decompose a ResearchGoal and return both the ResearchPlan and ValidatedDAG."""
        effective_run_id = run_id or f"run_{uuid.uuid4().hex[:12]}"
        effective_plan_id = plan_id or f"plan_{uuid.uuid4().hex[:12]}"

        user_prompt = self._build_user_prompt(goal)

        try:
            decomposition = await self.llm_client.generate_structured(
                system_prompt=PLANNER_SYSTEM_PROMPT,
                user_prompt=user_prompt,
                response_schema=PlannedDecomposition,
                temperature=0.0,
            )
        except Exception as e:
            raise PlannerError(
                f"LLM structured decomposition failed: {e}",
                {"run_id": effective_run_id, "goal_id": goal.goal_id, "error": str(e)},
            ) from e

        if not decomposition.subtasks:
            raise PlannerError(
                "Planner generated an empty subtask list",
                {"run_id": effective_run_id, "goal_id": goal.goal_id},
            )

        if len(decomposition.subtasks) > goal.max_subtasks:
            raise PlannerError(
                f"Plan exceeds goal max_subtasks ({len(decomposition.subtasks)} > {goal.max_subtasks})",
                {
                    "run_id": effective_run_id,
                    "goal_id": goal.goal_id,
                    "generated_count": len(decomposition.subtasks),
                    "max_allowed": goal.max_subtasks,
                },
            )

        # Build SubtaskNode dictionary and check for duplicate IDs
        nodes: dict[str, SubtaskNode] = {}
        for planned in decomposition.subtasks:
            if planned.subtask_id in nodes:
                raise PlannerError(
                    f"Duplicate subtask_id detected in planner output: '{planned.subtask_id}'",
                    {"duplicate_id": planned.subtask_id, "run_id": effective_run_id},
                )
            if not planned.objective.strip():
                raise PlannerError(
                    f"Subtask '{planned.subtask_id}' has an empty objective",
                    {"subtask_id": planned.subtask_id, "run_id": effective_run_id},
                )

            nodes[planned.subtask_id] = SubtaskNode(
                subtask_id=planned.subtask_id,
                task_type=planned.task_type,
                objective=planned.objective,
                search_queries=planned.search_queries,
                timeout_seconds=planned.timeout_seconds,
                max_retries=planned.max_retries,
                assigned_role=planned.assigned_role,
                input_context=planned.input_context,
            )

        # Build DependencyEdges from prerequisite_ids
        edges_list: list[DependencyEdge] = []
        for planned in decomposition.subtasks:
            target_id = planned.subtask_id
            for source_id in planned.prerequisite_ids:
                if source_id == target_id:
                    raise DAGValidationError(
                        message=f"Self-dependency detected: node '{target_id}' depends on itself",
                        error_code="SELF_DEPENDENCY",
                        violating_nodes=[target_id],
                    )
                if source_id not in nodes:
                    raise DAGValidationError(
                        message=f"Dependency edge references non-existent source node '{source_id}'",
                        error_code="MISSING_SOURCE_NODE",
                        violating_nodes=[source_id],
                    )
                edges_list.append(
                    DependencyEdge(
                        source_id=source_id,
                        target_id=target_id,
                        edge_type=EdgeType.DATA,
                    )
                )

        provisional_plan = ResearchPlan(
            plan_id=effective_plan_id,
            run_id=effective_run_id,
            goal=goal,
            nodes=nodes,
            edges=tuple(edges_list),
            metadata=PlanMetadata(
                created_by_agent="planner",
                total_estimated_depth=1,
                notes=decomposition.rationale or None,
            ),
            is_validated=False,
        )

        # Validate with DAGValidator
        validated_dag = self.validator.validate_plan(provisional_plan)

        # Construct final validated plan with confirmed critical path depth
        validated_plan = ResearchPlan(
            plan_id=effective_plan_id,
            run_id=effective_run_id,
            goal=goal,
            nodes=nodes,
            edges=tuple(edges_list),
            metadata=PlanMetadata(
                created_by_agent="planner",
                total_estimated_depth=validated_dag.metrics.critical_path_depth,
                notes=decomposition.rationale or None,
            ),
            is_validated=True,
        )

        return validated_plan, validated_dag
