"""Provider-neutral LLM data schemas and client protocol."""

import uuid
from typing import Any, Protocol, TypeVar, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T", bound=BaseModel)


def _gen_call_id() -> str:
    return f"call_{uuid.uuid4().hex[:12]}"


class ToolCall(BaseModel):
    """Structured representation of a function or tool invocation requested by an LLM."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    call_id: str = Field(
        default_factory=_gen_call_id, description="Unique tool call identifier"
    )
    tool_name: str = Field(..., min_length=1, description="Name of the target tool")
    arguments: dict[str, Any] = Field(
        default_factory=dict, description="Parsed keyword arguments for the tool"
    )


class LLMRequest(BaseModel):
    """Provider-neutral request payload submitted to an LLM provider."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    system_prompt: str = Field(
        default="", description="System instructions and persona guidelines"
    )
    user_prompt: str = Field(
        ..., min_length=1, description="Main user prompt or query context"
    )
    temperature: float = Field(
        default=0.0, ge=0.0, le=2.0, description="Sampling temperature"
    )
    max_tokens: int | None = Field(
        default=None, gt=0, description="Maximum completion tokens"
    )
    response_schema_name: str | None = Field(
        default=None, description="Optional target schema name for structured output"
    )


class LLMResponse(BaseModel):
    """Standardized response envelope returned by an LLM provider."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    content: str = Field(default="", description="Raw generated text completion")
    structured_output: dict[str, Any] | None = Field(
        default=None, description="Parsed structured JSON/Pydantic payload if requested"
    )
    tool_calls: tuple[ToolCall, ...] = Field(
        default_factory=tuple,
        description="Tool invocation requests generated by the model",
    )
    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    model_name: str = Field(
        default="mock-llm", description="Model identifier that produced this completion"
    )


@runtime_checkable
class LLMClientProtocol(Protocol):
    """Protocol for interacting with Large Language Model inference providers."""

    async def generate_text(self, request: LLMRequest) -> LLMResponse:
        """Generate unstructured text or tool-call completion."""
        ...

    async def generate_structured(
        self,
        system_prompt: str,
        user_prompt: str,
        response_schema: type[T],
        temperature: float = 0.0,
    ) -> T:
        """Generate structured response guaranteed to deserialize into the specified Pydantic schema."""
        ...
