"""Common domain types, enums, exceptions, and evidence models."""

from app.common.enums import (
    AgentRole,
    EdgeType,
    RunStage,
    SourceTrustLevel,
    TaskStatus,
    TaskType,
    ToolPermission,
    VerificationStatus,
)
from app.common.errors import (
    CheckpointCorruptedError,
    CheckpointRecoveryError,
    DAGValidationError,
    DeadlockDetectedError,
    DuplicateExecutionError,
    ExecutionCancelledError,
    IdempotencyConflictError,
    InvalidExecutionPlanError,
    InvalidStateTransitionError,
    PermissionDeniedError,
    ResearchMindError,
    RetryExhaustedError,
    SchedulerError,
    SchemaVersionError,
    TaskTimeoutError,
    WorkerExecutionError,
)
from app.common.evidence import (
    EvidenceRecord,
    ExtractedClaim,
    SourceProvenance,
    VerificationAudit,
)

__all__ = [
    "AgentRole",
    "CheckpointCorruptedError",
    "CheckpointRecoveryError",
    "DAGValidationError",
    "DeadlockDetectedError",
    "DuplicateExecutionError",
    "EdgeType",
    "EvidenceRecord",
    "ExecutionCancelledError",
    "ExtractedClaim",
    "IdempotencyConflictError",
    "InvalidExecutionPlanError",
    "InvalidStateTransitionError",
    "PermissionDeniedError",
    "ResearchMindError",
    "RetryExhaustedError",
    "RunStage",
    "SchedulerError",
    "SchemaVersionError",
    "SourceProvenance",
    "SourceTrustLevel",
    "TaskStatus",
    "TaskTimeoutError",
    "TaskType",
    "ToolPermission",
    "VerificationAudit",
    "VerificationStatus",
    "WorkerExecutionError",
]
